### ISSUE TITLE
Base UI not using flex

### ISSUE THREAD

**Issue by olivierobert** [benbkk/nimbl3-frontend#1]
Here is the current state of the frontend:

![ui-frontend](https://cloud.githubusercontent.com/assets/696529/22970561/2eb4befa-f3a5-11e6-9e32-e1d245d6deda.png)

Even the base is not following the guidelines of using flex for the layout

**Comment by benbkk** [comment]
Hi Carlos Yes i  am aware of that - just forgot to mention it on read me.
I didn't go with flex because, firstly I don't really see the need. Secondly based on my experience, until this moment, flex is never really a good reliable solution for anything that works well across all browsers. I know that it is instructed. But I really dont see the need. 

Well it doesnt matter anymore anyway isn't it.
But thanks, at least I've tried.
